/* =====================================================
   GAME CONFIG
   ===================================================== */

const GAME = {
  id: "alan-wake-2",
  storageKey: "alan-wake-2-checklist",

  statuses: ["NotStarted", "InProgress", "OnHold", "Completed", "Hundred"],

  completedStatuses: ["Completed", "Hundred"],

  categories: {
    lunchBox: "Lunch Boxes",
    charm: "Charms",
    cultStash: "Cult Stashes",
    echo: "Echos",
    koskelaAd: "Koskela Ads",
    manuscript: "Manuscripts",
    map: "Maps",
    radioShow: "Radio Shows",
    writersJourney: "Writer's Journey",
    nurseryDoll: "Nursery Dolls",
    nurseryRhyme: "Nursery Rhymes",
    deerHead: "Deer Heads",
    mayorSetterSign: "Mayor Setter Signs",
    wordsOfPower: "Words of Power",
    suitcaseStash: "Suitcase Stashes",
    weapon: "Weapons",
    song: "Songs"
  },

  data: {
  lunchBox: [
    { name: "Waterfall Vista", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: ""},
    { name: "Witch’s Hut", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: ""},
    { name: "FBC Station", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: ""},
    { name: "Witchfinder's Station", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: ""},
    { name: "Waterfall", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: ""},
    { name: "Campground", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: ""},
    { name: "Landslide", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: ""},
    { name: "Rental Cabins", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: ""},
    { name: "Radio Tower", tag: "WATERY, Saga", status: "NotStarted", note: ""},
    { name: "Above the Ranger's Cabin", tag: "WATERY, Saga", status: "NotStarted", note: ""},
    { name: "Coffee World", tag: "WATERY, Saga", status: "NotStarted", note: ""},
    { name: "Lighthouse Trailer Park", tag: "WATERY, Saga", status: "NotStarted", note: ""},
    { name: "Kalevala Knights Workshop", tag: "WATERY, Saga", status: "NotStarted", note: ""},
    { name: "Lighthouse", tag: "WATERY, Saga", status: "NotStarted", note: ""},
    { name: "Valhalla Nursing Home", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: ""},
    { name: "Ranger Station", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: ""},
    { name: "Shoreline", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: ""},
    { name: "Center Bright Falls (Forest)", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: ""},
    { name: "Founder's Park", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: ""},
    { name: "Bunker Woods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: ""},
    { name: "Billie’s Boat Yard", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: ""}
  ],
  charm: [
    { name: "Logan’s Charm", tag: "RETURN 2, Saga", status: "NotStarted", note: ""},
    { name: "Hammer Charm", tag: "RETURN 2, Saga", status: "NotStarted", note: ""},
    { name: "Kalevala Knights Charm", tag: "RETURN 2, Saga", status: "NotStarted", note: ""},
    { name: "Coffee Mug Charm (#1)", tag: "RETURN 2, Saga", status: "NotStarted", note: ""},
    { name: "Coffee Mug Charm (#2)", tag: "RETURN 3, Saga", status: "NotStarted", note: ""},
    { name: "Deer Charm", tag: "RETURN 3, Saga", status: "NotStarted", note: ""},
    { name: "Coffee World Token Charm", tag: "RETURN 3, Saga", status: "NotStarted", note: ""},
    { name: "Lighthouse Charm", tag: "RETURN 3, Saga", status: "NotStarted", note: ""},
    { name: "Mr. Drippy Charm", tag: "RETURN 3, Saga", status: "NotStarted", note: ""},
    { name: "FBC Charm", tag: "RETURN 3, Saga", status: "NotStarted", note: ""},
    { name: "Coffee Mug Charm (#3)", tag: "RETURN 3, Saga", status: "NotStarted", note: ""},
    { name: "Lantern Charm", tag: "RETURN 5, Saga", status: "NotStarted", note: ""},
    { name: "Coffee Mug Charm (#4)", tag: "RETURN 5, Saga", status: "NotStarted", note: ""},
    { name: "Valhalla Nursing Home Charm", tag: "RETURN 5, Saga", status: "NotStarted", note: ""},
    { name: "Anchor Charm", tag: "RETURN 5, Saga", status: "NotStarted", note: ""},
    { name: "Mayor Setter Charm", tag: "RETURN 5, Saga", status: "NotStarted", note: ""},
    { name: "Deerfest Charm", tag: "RETURN 5, Saga", status: "NotStarted", note: ""},
    { name: "Coffee Mug Charm (#5)", tag: "RETURN 5, Saga", status: "NotStarted", note: ""}
  ],
  cultStash: [
    { name: "Invitation", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: "Combination Padlock (Symbols)"},
    { name: "The Heart", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: "Memory Puzzle"},
    { name: "The Heart", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: "Keyed Padlock (Streamside Stash Key)"},
    { name: "The Heart", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: "Combination Padlock (Numbers)"},
    { name: "Old Gods ", tag: "CAULDRON LAKE, Saga", status: "NotStarted", note: "Keyed Padlock (Lake Cabins Stash Key)"},
    { name: "Local Girl", tag: "WATERY, Saga", status: "NotStarted", note: "Memory Puzzle"},
    { name: "Local Girl", tag: "WATERY, Saga", status: "NotStarted", note: "Combination Padlock (Numbers)"},
    { name: "Local Girl", tag: "WATERY, Saga", status: "NotStarted", note: "Combination Padlock (Numbers)"},
    { name: "Local Girl", tag: "WATERY, Saga", status: "NotStarted", note: "Keyed Padlock (Coffee World Stash Key)"},
    { name: "Local Girl", tag: "WATERY, Saga", status: "NotStarted", note: "Keyed Padlock (Trailer Park Stash Key)"},
    { name: "Local Girl", tag: "WATERY, Saga", status: "NotStarted", note: "Combination Padlock (Symbols)"},
    { name: "Local Girl", tag: "WATERY, Saga", status: "NotStarted", note: "Combination Padlock (Numbers)"},
    { name: "Old God", tag: "WATERY, Saga", status: "NotStarted", note: "Combination Padlock (Numbers)"},
    { name: "Old Gods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Memory Puzzle"},
    { name: "Old Gods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Combination Padlock (Numbers)"},
    { name: "Old Gods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Keyed Padlock (Bunker Woods Stash Key)"},
    { name: "Old Gods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Combination Padlock (Symbols)"},
    { name: "Old Gods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Keyed Padlock (Ranger Station Stash Key)"},
    { name: "Old Gods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Memory Puzzle"},
    { name: "Old Gods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Combination Padlock (Numbers)"},
    { name: "Old Gods", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Combination Padlock (Symbols)"},
    { name: "Scratch", tag: "BRIGHT FALLS, Saga", status: "NotStarted", note: "Combination Padlock (Numbers)"}
  ],
  echo: [
    { name: "The Manuscript", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "FBI Agent", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Murder Cult", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Markings", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Torchbearers", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Summoning Ritual", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Something In The Air", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Bad Luck", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Tree", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Alice Wake", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Another Murder", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Pre-Show Ritual", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Haunted", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "The Devil", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Room 666", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "The Climax", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Quid Pro Quo", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Thomas Zane", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "The Cult Of The World", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Crooked Cops", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Nightless Night", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Clips Of The Lost Film", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Down The Chute", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Death of a Cultist", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "The Grandmaster", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Trapped", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Cold Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Hard Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Closed Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Final Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Murder Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Worst Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""}
  ],
  koskelaAd: [
    { name: "Adventure Tours", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Coffee World", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Parade Floats", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Ahma Beer", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Bright Falls Blend", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Return Review", tag: "Saga", status: "NotStarted", note: ""}
  ],
  manuscript: [
  { name: "Title Page Of Return", tag: "RETURN 1, Alan, Saga", status: "NotStarted", note: "Cannot be obtained"},
  { name: "The Message", tag: "RETURN 1, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga Fights Nightingale With Light", tag: "RETURN 1, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga Pursues Nightingale", tag: "RETURN 1, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga At The General Store", tag: "RETURN 1, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga Anderson's Deja Vu", tag: "RETURN 1, Alan, Saga, NG", status: "NotStarted", note: ""},
  { name: "Nightingale Enters The Lake", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Nightingale In The Dark Place", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga Finds A Safe Haven", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga Opens The Cauldron Lake Overlap", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga Burns Away The Dark Substance", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "The Overlap", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "The Murder Sites", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Ed Returns To Cauldron Lake", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Tammy Rides The Ferry", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Cauldron Lake", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "The Cult Of The Tree", tag: "RETURN 2, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Dark Poem 1", tag: "RETURN 2, Alan, Saga, NG", status: "NotStarted", note: ""},
  { name: "The Trailer", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Scratch On The Hunt", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "The Koskela's Parade Float", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Deputies Make A Grave Mistake", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Deputies Corrupted", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Deputies In The Morgue", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Mocha's Funeral", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "The Cult Finds The Clicker", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Koskelas Break Into The FBC Lab", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "The Dark Presence Attacks", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga In The Watery Woods", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga Fights Taken At The Workshop", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Watery", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Coffee World Attacked", tag: "RETURN 3, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Breakthrough in the Lake House*", tag: "RETURN 3, Alan, Saga, NG", status: "NotStarted", note: ""},
  { name: "Saga At The Nursing Home", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Tor Is Bewitched", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Odin Stuck In Bed", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Saga Opens The Valhalla Nursing Home Overlap", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "The History Of The Valhalla Nursing Home", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Barry's Struggles With Artists", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Building The Valhalla Nursing Home", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Cynthia Corrupted", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Cynthia And Tom", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Cynthia's Lamp", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Gail Taken", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Bright Falls", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Rose At Bingo Night", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Emmett Taken", tag: "RETURN 5, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Dark Poem 2", tag: "RETURN 5, Alan, Saga, NG", status: "NotStarted", note: ""},
  { name: "Rose Receives A Message", tag: "RETURN 6, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Sheriff's Station Attacked", tag: "RETURN 6, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Dark Poem 3", tag: "RETURN 6, Alan, Saga, NG", status: "NotStarted", note: ""},
  { name: "The Cult Of The Tree Is Born", tag: "RETURN 7, Alan, Saga", status: "NotStarted", note: ""},
  { name: "The Cult Storms The Lodge", tag: "RETURN 7, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Ilmo Resists The Dark Presence", tag: "RETURN 7, Alan, Saga", status: "NotStarted", note: ""},
  { name: "Odin Loses An Eye", tag: "RETURN 7, Alan, Saga", status: "NotStarted", note: ""},
  { name: "It's Not a Lake", tag: "RETURN 7, Alan, Saga, NG", status: "NotStarted", note: ""},
  { name: "Door Traverses The Dark Place", tag: "RETURN 9, Alan, Saga", status: "NotStarted", note: ""},
  ],
  map:  [
    { name: "Cauldron Lake", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Bright Falls", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Sheriff’s Station", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Watery", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Valhalla Nursing Home", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Wellness Center", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Talk Show Studio", tag: "Alan", status: "NotStarted", note: ""},
    { name: "The Dark Place", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Subway", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Oceanview Hotel", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Poet’s Cinema", tag: "Alan", status: "NotStarted", note: ""}
  ],
  radioShow:  [
    { name: "Tapio's Weather Report", tag: "Alan, Saga", status: "NotStarted", note: ""},
    { name: "Donna's Jerky Review", tag: "Alan, Saga", status: "NotStarted", note: ""},
    { name: "Terry's Cuckoo Clocks", tag: "Alan, Saga", status: "NotStarted", note: ""},
    { name: "Jim's Mayoral Candidacy", tag: "Alan, Saga", status: "NotStarted", note: ""},
    { name: "Gil's Weird Joke", tag: "Alan, Saga", status: "NotStarted", note: ""},
    { name: "Technical Issues", tag: "Alan, Saga", status: "NotStarted", note: ""},
    { name: "Deerfest Floats", tag: "Alan, Saga", status: "NotStarted", note: ""},
    { name: "Terry's Guest Call", tag: "Alan, Saga", status: "NotStarted", note: ""},
    { name: "Pat's Late Start", tag: "Alan, Saga", status: "NotStarted", note: ""}
  ],
  writersJourney:  [
    { name: "The Dark Place", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Spiral", tag: "Alan, NG", status: "NotStarted", note: ""},
    { name: "Writing", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Murder Sites", tag: "Alan", status: "NotStarted", note: ""},
    { name: "The Dark Presence", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Visions", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Drowning", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Stop Writing", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Initiation", tag: "Alan", status: "NotStarted", note: ""}
  ],
  nurseryDoll:  [
    { name: "", tag: "Alan", status: "NotStarted", note: ""}
  ],
  nurseryRhyme:  [
    { name: "", tag: "Alan", status: "NotStarted", note: ""}
  ],
  deerHead:  [
    { name: "", tag: "Alan", status: "NotStarted", note: ""}
  ],
  mayorSetterSign:  [
    { name: "", tag: "Alan", status: "NotStarted", note: ""}
  ],
  wordsOfPower:  [
    { name: "", tag: "Alan", status: "NotStarted", note: ""}
  ],
  suitcaseStash:  [
    { name: "", tag: "Alan", status: "NotStarted", note: ""}
  ],
  weapon:  [
    { name: "Pistol", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Sawed-Off Shotgun", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Hunting Crossbow", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Hunting Rifle", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Pump-Action Shotgun", tag: "Saga", status: "NotStarted", note: ""},
    { name: "Flashlight", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Revolver", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Flare Gun", tag: "Alan", status: "NotStarted", note: ""},
    { name: "Double-Barreled Shotgun", tag: "Alan", status: "NotStarted", note: ""}
  ],
  song:  [
    { name: "", tag: "Alan", status: "NotStarted", note: ""}
  ]
 }
};
