export const echo = [
    { name: "The Manuscript", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "FBI Agent", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Murder Cult", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Markings", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Torchbearers", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Summoning Ritual", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Something In The Air", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Bad Luck", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Tree", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Alice Wake", tag: "DRAFT ONE, Alan", status: "NotStarted", note: ""},
    { name: "Another Murder", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Pre-Show Ritual", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Haunted", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "The Devil", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Room 666", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "The Climax", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Quid Pro Quo", tag: "DRAFT TWO, Alan", status: "NotStarted", note: ""},
    { name: "Thomas Zane", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "The Cult Of The World", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Crooked Cops", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Nightless Night", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Clips Of The Lost Film", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Down The Chute", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Death of a Cultist", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "The Grandmaster", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Trapped", tag: "DRAFT THREE, Alan", status: "NotStarted", note: ""},
    { name: "Cold Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Hard Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Closed Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Final Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Murder Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""},
    { name: "Worst Case", tag: "CASEY BILLBOARDS, Alan", status: "NotStarted", note: ""}
];